In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta
today = pd.Timestamp.now().strftime("%Y-%m-%d")
data = yf.download(tickers = 'AAPL', start = '2024-01-01',end = today, interval = '1d')
data

[*********************100%%**********************]  1 of 1 completed


Open        High         Low       Close   Adj Close  \
Date                                                                     
2024-01-02  187.149994  188.440002  183.889999  185.639999  185.403412   
2024-01-03  184.220001  185.880005  183.429993  184.250000  184.015198   
2024-01-04  182.149994  183.089996  180.880005  181.910004  181.678177   
2024-01-05  181.990005  182.759995  180.169998  181.179993  180.949097   
2024-01-08  182.089996  185.600006  181.500000  185.559998  185.323517   
2024-01-09  183.919998  185.149994  182.729996  185.139999  184.904053   
2024-01-10  184.350006  186.399994  183.919998  186.190002  185.952713   
2024-01-11  186.539993  187.050003  183.619995  185.589996  185.353485   
2024-01-12  186.059998  186.740005  185.190002  185.919998  185.683060   
2024-01-16  182.160004  184.259995  180.929993  183.630005  183.395981   
2024-01-17  181.270004  182.929993  180.300003  182.679993  182.447189   
2024-01-18  186.089996  189.139999  185.830002  188.630005  188.389618   
2024-01-19  189.330002  191.949997  188.820007  191.559998  191.315872   
2024-01-22  192.300003  195.330002  192.259995  193.889999  193.642899   
2024-01-23  195.020004  195.750000  193.830002  195.179993  194.931259   
2024-01-24  195.419998  196.380005  194.339996  194.500000  194.252121   
2024-01-25  195.220001  196.270004  193.110001  194.169998  193.922546   
2024-01-26  194.270004  194.759995  191.940002  192.419998  192.174774   
2024-01-29  192.009995  192.199997  189.580002  191.729996  191.485657   
2024-01-30  190.940002  191.800003  187.470001  188.039993  187.800354   
2024-01-31  187.039993  187.100006  184.350006  184.399994  184.164993   
2024-02-01  183.990005  186.949997  183.820007  186.860001  186.621872   
2024-02-02  179.860001  187.330002  179.250000  185.850006  185.613159   
2024-02-05  188.149994  189.250000  185.839996  187.679993  187.440811   
2024-02-06  186.860001  189.309998  186.770004  189.300003  189.058762   
2024-02-07  190.639999  191.050003  188.610001  189.410004  189.168625   
2024-02-08  189.389999  189.539993  187.350006  188.320007  188.080017   
2024-02-09  188.649994  189.990005  188.000000  188.850006  188.850006   

               Volume  
Date                   
2024-01-02   82488700  
2024-01-03   58414500  
2024-01-04   71983600  
2024-01-05   62303300  
2024-01-08   59144500  
2024-01-09   42841800  
2024-01-10   46792900  
2024-01-11   49128400  
2024-01-12   40444700  
2024-01-16   65603000  
2024-01-17   47317400  
2024-01-18   78005800  
2024-01-19   68741000  
2024-01-22   60133900  
2024-01-23   42355600  
2024-01-24   53631300  
2024-01-25   54822100  
2024-01-26   44594000  
2024-01-29   47145600  
2024-01-30   55859400  
2024-01-31   55467800  
2024-02-01   64885400  
2024-02-02  102518000  
2024-02-05   69668800  
2024-02-06   43490800  
2024-02-07   53439000  
2024-02-08   40962000  
2024-02-09   45099900

In [2]:
# Adding indicators

data['RSI']=ta.rsi(data.Close, length=15)
data['EMAF']=ta.ema(data.Close, length=20)
data['EMAM']=ta.ema(data.Close, length=100)
data['EMAS']=ta.ema(data.Close, length=150)

data['TargetNextClose'] = data['Adj Close'].shift(-1)

data.dropna(inplace=True)
data.reset_index(inplace = True)
data.drop(['Volume', 'Close'], axis=1, inplace=True)

In [3]:
data

Date        Open        High         Low   Adj Close        RSI  \
0   2020-08-05  109.377502  110.392502  108.897499  107.634499  76.740188   
1   2020-08-06  110.404999  114.412498  109.797501  111.389786  79.840111   
2   2020-08-07  113.205002  113.675003  110.292503  108.857254  72.335443   
3   2020-08-10  112.599998  113.775002  110.000000  110.439484  73.859351   
4   2020-08-11  111.970001  112.482498  109.107498  107.155014  65.798000   
..         ...         ...         ...         ...         ...        ...   
871 2024-01-23  195.020004  195.750000  193.830002  194.931259  61.902835   
872 2024-01-24  195.419998  196.380005  194.339996  194.252121  60.324379   
873 2024-01-25  195.220001  196.270004  193.110001  193.922546  59.535029   
874 2024-01-26  194.270004  194.759995  191.940002  192.174774  55.415097   
875 2024-01-29  192.009995  192.199997  189.580002  191.485657  53.841089   

           EMAF        EMAM        EMAS  TargetNextClose  
0     99.058865   85.899634   79.150333       111.389786  
1    100.472544   86.454146   79.610627       108.857254  
2    101.485874   86.942430   80.027870       110.439484  
3    102.556505   87.453026   80.460978       107.155014  
4    103.205885   87.887124   80.843945       110.716240  
..          ...         ...         ...              ...  
871  189.050455  185.211039  182.214389       194.252121  
872  189.569459  185.394978  182.377112       193.922546  
873  190.007606  185.568741  182.533309       192.174774  
874  190.237357  185.704410  182.664259       191.485657  
875  190.379513  185.823728  182.784335       187.800354  

[876 rows x 10 columns]

In [4]:
data_set = data.iloc[:, 0:11]#.values
pd.set_option('display.max_columns', None)

data_set.head(20)
#print(data_set.shape)
#print(data.shape)
#print(type(data_set))

Date        Open        High         Low   Adj Close        RSI  \
0  2020-08-05  109.377502  110.392502  108.897499  107.634499  76.740188   
1  2020-08-06  110.404999  114.412498  109.797501  111.389786  79.840111   
2  2020-08-07  113.205002  113.675003  110.292503  108.857254  72.335443   
3  2020-08-10  112.599998  113.775002  110.000000  110.439484  73.859351   
4  2020-08-11  111.970001  112.482498  109.107498  107.155014  65.798000   
5  2020-08-12  110.497498  113.275002  110.297501  110.716240  69.646646   
6  2020-08-13  114.430000  116.042503  113.927498  112.675644  71.534890   
7  2020-08-14  114.830002  115.000000  113.044998  112.575218  71.291362   
8  2020-08-17  116.062500  116.087502  113.962502  112.281311  70.538323   
9  2020-08-18  114.352501  116.000000  114.007500  113.216927  71.562815   
10 2020-08-19  115.982498  117.162498  115.610001  113.358978  71.722773   
11 2020-08-20  115.750000  118.392502  115.732498  115.874374  74.449460   
12 2020-08-21  119.262497  124.867500  119.250000  121.845673  79.481740   
13 2020-08-24  128.697495  128.785004  123.937500  123.302963  80.486682   
14 2020-08-25  124.697502  125.180000  123.052498  122.291420  77.657996   
15 2020-08-26  126.180000  126.992500  125.082497  123.954468  78.960500   
16 2020-08-27  127.142502  127.485001  123.832497  122.472664  74.797636   
17 2020-08-28  126.012497  126.442497  124.577499  122.274292  74.236213   
18 2020-08-31  127.580002  131.000000  126.000000  126.420876  77.943635   
19 2020-09-01  132.759995  134.800003  130.529999  131.456558  81.422112   

          EMAF       EMAM       EMAS  TargetNextClose  
0    99.058865  85.899634  79.150333       111.389786  
1   100.472544  86.454146  79.610627       108.857254  
2   101.485874  86.942430  80.027870       110.439484  
3   102.556505  87.453026  80.460978       107.155014  
4   103.205885  87.887124  80.843945       110.716240  
5   104.139611  88.384607  81.269985       112.675644  
6   105.174886  88.911843  81.716873       112.575218  
7   106.101802  89.426608  82.156484       112.281311  
8   106.911868  89.925240  82.586299       113.216927  
9   107.735738  90.432908  83.023070       113.358978  
10  108.494953  90.933395  83.455976       115.874374  
11  109.426386  91.474813  83.917155       121.845673  
12  110.849588  92.126203  84.452954       123.302963  
13  112.278913  92.794149  85.001359       122.291420  
14  113.473778  93.428424  85.528824       123.954468  
15  114.716513  94.083752  86.071787       122.472664  
16  115.696845  94.696153  86.587525       122.274292  
17  116.564527  95.292417  87.093750       126.420876  
18  117.752667  95.960686  87.649329       131.456558  
19  119.317174  96.717504  88.265629       128.732956

In [5]:
#Target column Categories
#y =[1 if data.Open[i]>data.Close[i] else 0 for i in range(0, len(data))]
#yi = [data.Open[i]-data.Close[i] for i in range(0, len(data))]
#print(yi)
#print(len(yi))

In [6]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))

"""
data_set_scaled = sc.fit_transform(data_set)
print(data_set_scaled)
"""

import joblib
from sklearn.preprocessing import MinMaxScaler
symbol = 'AAPL'

df = data_set
features = df.drop(['Date'], axis=1).columns.tolist()
target = ['TargetNextClose']

X = df[features].values
y = df[target].values

y_scaler = MinMaxScaler(feature_range=(0, 1))
y_scaled = y_scaler.fit_transform(y)

# Save the target variable scaler for this symbol
y_scaler_filename = f"/Users/anujthakkar/Documents/Purdue/Projects/wisebucks.ai/LSTM/scalers/{symbol}_y_scaler.save"
joblib.dump(y_scaler, y_scaler_filename)

# Apply scaling to the features 'X'
x_scaler = MinMaxScaler(feature_range=(0, 1))
X_scaled = x_scaler.fit_transform(X)

# Save the feature scaler for this symbol
x_scaler_filename = f"/Users/anujthakkar/Documents/Purdue/Projects/wisebucks.ai/LSTM/scalers/{symbol}_x_scaler.save"
joblib.dump(x_scaler, x_scaler_filename)

data_set_scaled = np.concatenate((X_scaled, y_scaled), axis=1)

In [7]:
# multiple feature from data provided to the model
X = []
#print(data_set_scaled[0].size)
#data_set_scaled=data_set.values
backcandles = 30
print(data_set_scaled.shape[0])
for j in range(8):#data_set_scaled[0].size):#2 columns are target not X
    X.append([])
    for i in range(backcandles, data_set_scaled.shape[0]):#backcandles+2
        X[j].append(data_set_scaled[i-backcandles:i, j])

#move axis from 0 to position 2
X=np.moveaxis(X, [0], [2])

#Erase first elements of y because of backcandles to match X length
#del(yi[0:backcandles])
#X, yi = np.array(X), np.array(yi)
# Choose -1 for last column, classification else -2...
X, yi =np.array(X), np.array(data_set_scaled[backcandles:,-1])
y=np.reshape(yi,(len(yi),1))
#y=sc.fit_transform(yi)
#X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(X)
print(X.shape)
print(y)
print(y.shape)

876
[[[0.05174905 0.00226433 0.06174122 ... 0.         0.         0.        ]
  [0.06274067 0.04721566 0.0713259  ... 0.01499582 0.00554933 0.00444153]
  [0.09269363 0.03896904 0.07659749 ... 0.02574487 0.01043589 0.00846765]
  ...
  [0.1089003  0.06418426 0.10330143 ... 0.20142593 0.13947689 0.116873  ]
  [0.14751819 0.09661188 0.1119276  ... 0.19889263 0.14258881 0.11997583]
  [0.11435603 0.06496699 0.09520769 ... 0.19315562 0.14496335 0.12260174]]

 [[0.06274067 0.04721566 0.0713259  ... 0.01499582 0.00554933 0.00444153]
  [0.09269363 0.03896904 0.07659749 ... 0.02574487 0.01043589 0.00846765]
  [0.08622162 0.04008721 0.07348244 ... 0.03710176 0.01554572 0.01264686]
  ...
  [0.14751819 0.09661188 0.1119276  ... 0.19889263 0.14258881 0.11997583]
  [0.11435603 0.06496699 0.09520769 ... 0.19315562 0.14496335 0.12260174]
  [0.05541292 0.02247562 0.05974441 ... 0.18615664 0.14693614 0.12496409]]

 [[0.09269363 0.03896904 0.07659749 ... 0.02574487 0.01043589 0.00846765]
  [0.08622162 0.04

In [8]:
#also comprehensions for X
#X = np.array([data_set_scaled[i-backcandles:i,:4].copy() for i in range(backcandles,len(data_set_scaled))])
#print(X)
#print(X.shape)

In [9]:
# split data into train test sets
splitlimit = int(len(X)*0.9)
print(splitlimit)
X_train, X_test = X[:splitlimit], X[splitlimit:]
y_train, y_test = y[:splitlimit], y[splitlimit:]
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

# get dates for the test set
dates = data['Date']
dates = dates[splitlimit+backcandles:]


761
(761, 30, 8) (85, 30, 8)
(761, 1) (85, 1)


In [10]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import TimeDistributed

import tensorflow as tf
import keras
from keras import optimizers
from keras.callbacks import History
from keras.models import Model
from keras.layers import Dense, Dropout, LSTM, Input, Activation, concatenate
import numpy as np
#tf.random.set_seed(20)
np.random.seed(10)

input_shape = (X_train.shape[1], X_train.shape[2])
model = Sequential()
# must set return_sequence to False for last LSTM layer
model.add(LSTM(100, input_shape=input_shape, activation='tanh', return_sequences=True))
model.add(Dropout(0.05))
model.add(LSTM(units=100,return_sequences=True))
model.add(Dropout(0.4))
model.add(LSTM(units=50,return_sequences=False))
model.add(Dropout(0.05))
model.add(Dense(1, activation='relu'))
adam = optimizers.Adam()
model.compile(optimizer=adam, loss='mse')
model.fit(x=X_train, y=y_train, batch_size=15, epochs=30, shuffle=True, validation_split = 0.1)

2024-02-12 00:41:41.352648: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


Epoch 1/30
46/46 [==============================] - 7s 53ms/step - loss: 0.0171 - val_loss: 0.0135
Epoch 2/30
46/46 [==============================] - 1s 25ms/step - loss: 0.0053 - val_loss: 0.0075
Epoch 3/30
46/46 [==============================] - 1s 24ms/step - loss: 0.0057 - val_loss: 0.0151
Epoch 4/30
46/46 [==============================] - 1s 30ms/step - loss: 0.0045 - val_loss: 0.0073
Epoch 5/30
46/46 [==============================] - 1s 26ms/step - loss: 0.0048 - val_loss: 0.0242
Epoch 6/30
46/46 [==============================] - 1s 24ms/step - loss: 0.0044 - val_loss: 0.0054
Epoch 7/30
46/46 [==============================] - 1s 25ms/step - loss: 0.0040 - val_loss: 0.0058
Epoch 8/30
46/46 [==============================] - 1s 24ms/step - loss: 0.0039 - val_loss: 0.0203
Epoch 9/30
46/46 [==============================] - 1s 24ms/step - loss: 0.0039 - val_loss: 0.0034
Epoch 10/30
46/46 [==============================] - 1s 24ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 11/

In [11]:
print(X_test.shape)
print(y_test.shape)
print(X.shape[0]-X_test.shape[0])
print(X.shape[0])





y_pred = model.predict(X_test)

# load y_scaler and x_scaler given symbol
y_scaler = joblib.load(y_scaler_filename)
x_scaler = joblib.load(x_scaler_filename)

# inverse transform the predictions
y_pred = y_scaler.inverse_transform(y_pred)
y_test = y_scaler.inverse_transform(y_test)



for i in range(len(y_pred)):    

    # get the value of the date from dates
    print(dates.iloc[i], y_pred[i], y_test[i])
   

# for y in range(len(y_pred)):
#    print(y_pred[y], y_test[y])

(85, 30, 8)
(85, 1)
761
846
3/3 [==============================] - 1s 11ms/step
2023-09-27 00:00:00 [168.92606] [170.2481842]
2023-09-28 00:00:00 [167.0354] [170.76683044]
2023-09-29 00:00:00 [166.16072] [173.30026245]
2023-10-02 00:00:00 [166.19066] [171.95375061]
2023-10-03 00:00:00 [167.97296] [173.210495]
2023-10-04 00:00:00 [167.94247] [174.45726013]
2023-10-05 00:00:00 [168.49081] [177.03059387]
2023-10-06 00:00:00 [169.55017] [178.52670288]
2023-10-09 00:00:00 [171.69524] [177.92825317]
2023-10-10 00:00:00 [173.48036] [179.33459473]
2023-10-11 00:00:00 [173.75575] [180.24224854]
2023-10-12 00:00:00 [174.72343] [178.38705444]
2023-10-13 00:00:00 [175.91731] [178.25740051]
2023-10-16 00:00:00 [175.08182] [176.69145203]
2023-10-17 00:00:00 [174.6167] [175.38484192]
2023-10-18 00:00:00 [173.32912] [175.00584412]
2023-10-19 00:00:00 [171.94621] [172.43251038]
2023-10-20 00:00:00 [171.24846] [172.55220032]
2023-10-23 00:00:00 [169.3047] [172.99105835]
2023-10-24 00:00:00 [168.41518] [

In [ ]:
plt.figure(figsize=(16,8))
plt.plot(dates, y_test, color = 'black', label = 'Test')
plt.plot(dates, y_pred, color = 'green', label = 'pred')
plt.legend()
plt.show()